version: '3.7'
services:
  plugin:
    build: .
    volumes: 
      - .:/code
    environment:
      - SMARTY_AUTH_ID
      - SMARTY_AUTH_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_CLOUDFRONT_DISTRIBUTION_ID
